package org.ProvaWebDB.model;
// Generated 27-mar-2018 18.13.33 by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.JoinColumn;

/**
 * Prodotto generated by hbm2java
 */
@Entity
@Table(name = "prodotto", schema = "public")
@NamedQueries(@NamedQuery(name = "findAll", query = "select p from Prodotto p"))
public class Prodotto implements java.io.Serializable {

	private long id;
	private String nome;
	private Categoria categoria;

	public Prodotto() {
	}

	public Prodotto(int id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	@Id
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 40)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}


	@ManyToOne
	@MapsId("id")
	@JoinColumn(name = "Categoria_id", referencedColumnName = "id")
	public Categoria getCategoria() {
	    return categoria;
	}

	public void setCategoria(Categoria param) {
	    this.categoria = param;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Prodotto other = (Prodotto) obj;
		if (id != other.id)
			return false;
		return true;
	}

	
}
