package org.ProvaWebDB.model;
// Generated 27-mar-2018 18.13.33 by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * Prodotto generated by hbm2java
 */
@Entity
@Table(name = "prodotto", schema = "public")
@NamedQueries(@NamedQuery(name = "findAll", query = "select p from Prodotto p"))
public class Prodotto implements java.io.Serializable {

	private int id;
	private String nome;

	public Prodotto() {
	}

	public Prodotto(int id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 40)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof Prodotto)) {
			return false;
		}
		Prodotto other = (Prodotto) obj;
		if (id != other.id) {
			return false;
		}
		return true;
	}

}
